/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'working-hours': WorkingHour;
    'home-page': HomePage;
    'about-page': AboutPage;
    'process-page': ProcessPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'working-hours': WorkingHoursSelect<false> | WorkingHoursSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'process-page': ProcessPageSelect<false> | ProcessPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins can manage users. Editors can manage content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image in a few words — needed for SEO and screen readers.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Every product page on the website is built from these entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Used in the page URL. Leave it alone unless you know the page is not live yet.
   */
  slug: string;
  category: 'pp-granules' | 'hdpe-sheets' | 'ro-filter-housing';
  /**
   * Lower numbers appear first.
   */
  displayOrder?: number | null;
  /**
   * Show this product in the home page grid.
   */
  isFeatured?: boolean | null;
  /**
   * One or two lines. Used on product cards.
   */
  shortDescription: string;
  heroImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Main description shown at the top of the product page.
   */
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Packing, minimum order quantity and dispatch details.
   */
  packingSupply?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Shown as swatches. Hex code is only for the on-screen swatch, not a colour promise.
   */
  colours?:
    | {
        name: string;
        /**
         * Six-digit hex code, e.g. #1C3557
         */
        hexCode: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as a table. Add only values you can stand behind.
   */
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        application: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  buyerTypes?:
    | {
        buyerType: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave blank to use the page heading and description automatically.
   */
  seo?: {
    /**
     * Around 60 characters works best in Google results.
     */
    metaTitle?: string | null;
    /**
     * Around 155 characters. Plain, factual sentence about the page.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries received from the website. Update the status as you follow up.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  companyName?: string | null;
  phone: string;
  email?: string | null;
  productInterest?: (number | null) | Product;
  quantity?: string | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'quoted' | 'closed') | null;
  internalNotes?: string | null;
  source?: ('contact-page' | 'product-page') | null;
  submittedAt?: string | null;
  /**
   * Hashed sender address, kept only for spam control.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  displayOrder?: T;
  isFeatured?: T;
  shortDescription?: T;
  heroImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  overview?: T;
  packingSupply?: T;
  colours?:
    | T
    | {
        name?: T;
        hexCode?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        application?: T;
        note?: T;
        id?: T;
      };
  buyerTypes?:
    | T
    | {
        buyerType?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  companyName?: T;
  phone?: T;
  email?: T;
  productInterest?: T;
  quantity?: T;
  message?: T;
  status?: T;
  internalNotes?: T;
  source?: T;
  submittedAt?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Company details used across the whole website — header, footer and contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * Shown as "X+ Years Experience".
   */
  experienceYears?: number | null;
  /**
   * Optional. Shown as "Since 20XX" when filled in.
   */
  establishedYear?: number | null;
  /**
   * Registered firm name, if you want it shown in the footer.
   */
  legalName?: string | null;
  /**
   * Optional. Leave blank to keep it off the website.
   */
  gstNumber?: string | null;
  footerAbout?: string | null;
  phonePrimary: string;
  phoneSecondary?: string | null;
  /**
   * Digits only, without +91.
   */
  whatsappPrimary?: string | null;
  whatsappSecondary?: string | null;
  email?: string | null;
  addressLines?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  /**
   * From Google Maps → Share → Embed a map → copy the src="..." link.
   */
  googleMapsEmbedUrl?: string | null;
  supplyAreas?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Drives both the hours table and the live Open / Closed badge on the contact page (India time).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-hours".
 */
export interface WorkingHour {
  id: number;
  days?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        isClosed?: boolean | null;
        /**
         * 24-hour, e.g. 09:00
         */
        openTime?: string | null;
        /**
         * 24-hour, e.g. 21:00
         */
        closeTime?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional line shown under the table, e.g. holiday timings.
   */
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    /**
     * Small line above the heading.
     */
    kicker?: string | null;
    heading: string;
    subheading?: string | null;
    image?: (number | null) | Media;
    primaryCtaLabel?: string | null;
    primaryCtaHref?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  /**
   * Three cards sitting just below the hero.
   */
  featureCards?:
    | {
        icon?: ('factory' | 'recycle' | 'truck' | 'shield' | 'layers' | 'clock') | null;
        heading: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  aboutSnippet: {
    kicker?: string | null;
    heading: string;
    body: string;
    image?: (number | null) | Media;
    linkLabel?: string | null;
  };
  productsSection: {
    kicker?: string | null;
    heading: string;
    intro?: string | null;
  };
  whyChooseUs: {
    kicker?: string | null;
    heading: string;
    points?:
      | {
          icon?: ('factory' | 'recycle' | 'truck' | 'shield' | 'layers' | 'clock') | null;
          heading: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  processStrip: {
    kicker?: string | null;
    heading: string;
    steps?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    linkLabel?: string | null;
  };
  supplyArea?: {
    heading?: string | null;
    text?: string | null;
  };
  ctaBand: {
    heading: string;
    text?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
    /**
     * Show both phone numbers inside the band.
     */
    showPhoneNumbers?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    /**
     * Small line above the heading.
     */
    kicker?: string | null;
    heading: string;
    subheading?: string | null;
    image?: (number | null) | Media;
  };
  /**
   * Each section is a heading with text, shown in order.
   */
  sections?:
    | {
        heading: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        imagePosition?: ('right' | 'left') | null;
        id?: string | null;
      }[]
    | null;
  ctaBand: {
    heading: string;
    text?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
    /**
     * Show both phone numbers inside the band.
     */
    showPhoneNumbers?: boolean | null;
  };
  /**
   * Leave blank to use the page heading and description automatically.
   */
  seo?: {
    /**
     * Around 60 characters works best in Google results.
     */
    metaTitle?: string | null;
    /**
     * Around 155 characters. Plain, factual sentence about the page.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-page".
 */
export interface ProcessPage {
  id: number;
  hero: {
    /**
     * Small line above the heading.
     */
    kicker?: string | null;
    heading: string;
    subheading?: string | null;
    image?: (number | null) | Media;
  };
  intro?: string | null;
  steps?:
    | {
        title: string;
        description: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  dependability?: {
    heading?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  ctaBand: {
    heading: string;
    text?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
    /**
     * Show both phone numbers inside the band.
     */
    showPhoneNumbers?: boolean | null;
  };
  /**
   * Leave blank to use the page heading and description automatically.
   */
  seo?: {
    /**
     * Around 60 characters works best in Google results.
     */
    metaTitle?: string | null;
    /**
     * Around 155 characters. Plain, factual sentence about the page.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  hero: {
    /**
     * Small line above the heading.
     */
    kicker?: string | null;
    heading: string;
    subheading?: string | null;
  };
  intro?: string | null;
  formHeading?: string | null;
  /**
   * Short line above the form.
   */
  formIntro?: string | null;
  /**
   * Landmark or directions note shown under the map.
   */
  directionsNote?: string | null;
  thankYouMessage?: string | null;
  /**
   * Leave blank to use the page heading and description automatically.
   */
  seo?: {
    /**
     * Around 60 characters works best in Google results.
     */
    metaTitle?: string | null;
    /**
     * Around 155 characters. Plain, factual sentence about the page.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  tagline?: T;
  logo?: T;
  experienceYears?: T;
  establishedYear?: T;
  legalName?: T;
  gstNumber?: T;
  footerAbout?: T;
  phonePrimary?: T;
  phoneSecondary?: T;
  whatsappPrimary?: T;
  whatsappSecondary?: T;
  email?: T;
  addressLines?:
    | T
    | {
        line?: T;
        id?: T;
      };
  googleMapsEmbedUrl?: T;
  supplyAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "working-hours_select".
 */
export interface WorkingHoursSelect<T extends boolean = true> {
  days?:
    | T
    | {
        day?: T;
        isClosed?: T;
        openTime?: T;
        closeTime?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        heading?: T;
        subheading?: T;
        image?: T;
        primaryCtaLabel?: T;
        primaryCtaHref?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  featureCards?:
    | T
    | {
        icon?: T;
        heading?: T;
        text?: T;
        id?: T;
      };
  aboutSnippet?:
    | T
    | {
        kicker?: T;
        heading?: T;
        body?: T;
        image?: T;
        linkLabel?: T;
      };
  productsSection?:
    | T
    | {
        kicker?: T;
        heading?: T;
        intro?: T;
      };
  whyChooseUs?:
    | T
    | {
        kicker?: T;
        heading?: T;
        points?:
          | T
          | {
              icon?: T;
              heading?: T;
              text?: T;
              id?: T;
            };
      };
  processStrip?:
    | T
    | {
        kicker?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        linkLabel?: T;
      };
  supplyArea?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  ctaBand?:
    | T
    | {
        heading?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
        showPhoneNumbers?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        heading?: T;
        subheading?: T;
        image?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
        imagePosition?: T;
        id?: T;
      };
  ctaBand?:
    | T
    | {
        heading?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
        showPhoneNumbers?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "process-page_select".
 */
export interface ProcessPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        heading?: T;
        subheading?: T;
        image?: T;
      };
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  dependability?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  ctaBand?:
    | T
    | {
        heading?: T;
        text?: T;
        buttonLabel?: T;
        buttonHref?: T;
        showPhoneNumbers?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        heading?: T;
        subheading?: T;
      };
  intro?: T;
  formHeading?: T;
  formIntro?: T;
  directionsNote?: T;
  thankYouMessage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}